- job:
    name: designate-base
    parent: devstack-tempest
    vars: &base_vars
      devstack_localrc:
        DESIGNATE_SERVICE_PORT_DNS: 5322
        TEMPEST_PLUGINS: /opt/stack/designate-tempest-plugin
        USE_PYTHON3: true
      devstack_plugins:
        designate: https://opendev.org/openstack/designate
      devstack_services:
        designate: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-bak: false
      tox_envlist: all
      tempest_test_regex: |
        designate_tempest_plugin.*
    required-projects: &base_required_projects
      - openstack/designate
      - openstack/designate-dashboard
      - name: openstack/designate-tempest-plugin
        override-checkout: 0.8.0
      - openstack/python-designateclient
    timeout: 4200
    irrelevant-files: &base_irrelevant_files
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$
      - ^releasenotes/.*$

- job:
    name: designate-base-ipv6-only
    parent: devstack-tempest-ipv6
    description: |
      Designate devstack-tempest base job for IPv6-only deployment
    irrelevant-files: *base_irrelevant_files
    required-projects: *base_required_projects
    vars: *base_vars

- job:
    name: designate-bind9
    post-run: playbooks/designate-bind9/post.yaml
    parent: designate-base

- job:
    name: designate-pdns4
    post-run: playbooks/designate-pdns4/post.yaml
    parent: designate-base
    vars:
      devstack_localrc:
        DESIGNATE_BACKEND_DRIVER: pdns4

- job:
    name: designate-pdns4-postgres
    parent: designate-pdns4
    vars:
      devstack_services:
        mysql: False
        postgresql: True
    voting: false

- job:
    name: designate-ipv6-only-bind9
    post-run: playbooks/designate-bind9/post.yaml
    parent: designate-base-ipv6-only

- job:
    name: designate-ipv6-only-pdns4
    post-run: playbooks/designate-pdns4/post.yaml
    parent: designate-base-ipv6-only
    vars:
      devstack_localrc:
        DESIGNATE_BACKEND_DRIVER: pdns4

- job:
    name: designate-grenade-pdns4
    parent: grenade
    required-projects:
      - opendev.org/openstack/grenade
      - opendev.org/openstack/designate
      - name: opendev.org/openstack/designate-tempest-plugin
        override-checkout: 0.8.0
      - opendev.org/openstack/python-designateclient
    vars:
      grenade_devstack_localrc:
        shared:
          DESIGNATE_SERVICE_PORT_DNS: 5322
          DESIGNATE_BACKEND_DRIVER: pdns4
      devstack_plugins:
        designate: https://opendev.org/openstack/designate.git
        designate-tempest-plugin: https://opendev.org/openstack/designate-tempest-plugin.git
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-api: false
        c-bak: false
        c-vol: false
        cinder: false
        designate: true
        designate-api: true
        designate-central: true
        designate-producer: true
        designate-mdns: true
        designate-sink: true
        designate-agent: true
        designate-worker: true
      tempest_plugins:
        - designate-tempest-plugin
      tempest_test_regex: ^designate_tempest_plugin.*\[.*\bsmoke\b.*\]
      tox_envlist: all
    timeout: 10800
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^etc/.*$
      - ^releasenotes/.*$

- project-template:
    name: designate-devstack-jobs
    queue: designate
    check:
      jobs:
        - designate-bind9
        - designate-pdns4
        - designate-grenade-pdns4
        - designate-ipv6-only-pdns4
        - designate-ipv6-only-bind9

    gate:
      jobs:
        - designate-bind9
        - designate-pdns4
        - designate-grenade-pdns4
        - designate-ipv6-only-pdns4
        - designate-ipv6-only-bind9

- project:
    templates:
      - designate-devstack-jobs
      - openstack-cover-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - neutron-tempest-plugin-designate-scenario-ussuri
    experimental:
      jobs:
        - designate-pdns4-postgres
